name: Scraper

on:
  schedule:
    - cron: "0 * * * *"  # 매 시간 0분에 실행 (UTC 기준)

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 slack_sdk

    - name: Run scraper
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python scraper.py
