name: Scraper

on:
  schedule:
    - cron: "0 * * * *"  # 매 시간 0분에 실행 (UTC 기준)
  workflow_dispatch:

jobs:
  scrape-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 slack_sdk

    - name: Send Slack notification before running the scraper
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: |
        curl -X POST -H 'Content-type: application/json' --data '{"text":"수동으로 모니터링이 시작되었습니다."}' https://slack.com/api/chat.postMessage?token=${SLACK_TOKEN}&channel=${CHANNEL_ID}

    - name: Run scraper
      env:
        SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
        CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
      run: python scraper.py
